/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 .\\congressi.glb --transform -D --root ..\\models\
*/

import React, {useRef, useEffect} from 'react'
import {MathUtils} from 'three'
import {useGLTF, useAnimations} from '@react-three/drei'
import {useFrame} from '@react-three/fiber'

export default function Model(scroll, props) {

  const group = useRef()
  const {nodes, materials, animations} = useGLTF('/models/congressi-transformed.glb')
  const {actions} = useAnimations(animations, group)

  useEffect(() => void (actions['CameraAction'].play().paused = true), [])

  useFrame((state) => {

    actions['CameraAction'].time = MathUtils.lerp(actions['CameraAction'].time, actions['CameraAction'].getClip().duration * scroll.current, 0.05)

  })

  return (

    <group ref={group} {...props} dispose={null}>

      <group name="Scene">
        <mesh name="Ground_disk" geometry={nodes.Ground_disk.geometry} material={materials.ground_mat} position={[0, 0, 2.66]} scale={0.1} />
        <group name="Seat" rotation={[Math.PI, 0, Math.PI]}>
          <mesh name="Seat_mesh" geometry={nodes.Seat_mesh.geometry} material={materials.seat_fabric} />
          <mesh name="Seat_mesh_1" geometry={nodes.Seat_mesh_1.geometry} material={materials.metal} />
        </group>

        <mesh name="Stage" geometry={nodes.Stage.geometry} material={materials.stage_mat} position={[0, 0, -0.02]} rotation={[-Math.PI, 0, 0]} scale={[-6, -7, -4.01]} />
        <mesh name="Stairs_L" geometry={nodes.Stairs_L.geometry} material={materials.stage_mat} position={[0, 0, -0.58]} />
        <mesh name="Stairs_R" geometry={nodes.Stairs_R.geometry} material={materials.stage_mat} position={[6, 0.95, 2]} scale={[0.5, 0.21, 1.97]} />
        <mesh name="Plane000" geometry={nodes.Plane000.geometry} material={nodes.Plane000.material} position={[-4.43, -0.23, 18.01]} rotation={[Math.PI, 0, Math.PI]} />
        <mesh name="Plane001" geometry={nodes.Plane001.geometry} material={nodes.Plane001.material} position={[0, -0.23, 5.51]} rotation={[0, 0, -Math.PI]} scale={-1} />
        <mesh name="Plane003" geometry={nodes.Plane003.geometry} material={nodes.Plane003.material} position={[0, -0.24, 7.74]} />
        <mesh name="Plane002" geometry={nodes.Plane002.geometry} material={nodes.Plane002.material} position={[0, -0.22, 7.74]} rotation={[-Math.PI, 0, 0]} scale={-1} />
        <mesh name="Podium" geometry={nodes.Podium.geometry} material={nodes.Podium.material} position={[-2.4, 1.6, 3]} rotation={[0, 0.13, 0]} scale={0.19} />
        <mesh name="Stairs_L001" geometry={nodes.Stairs_L001.geometry} material={materials.stage_mat} position={[0, 0, -0.58]} />
        <mesh name="Stairs_L002" geometry={nodes.Stairs_L002.geometry} material={materials.stage_mat} position={[0, 0, -0.58]} />
        <mesh name="Stairs_L003" geometry={nodes.Stairs_L003.geometry} material={materials.stage_mat} position={[0, 0, -0.58]} />
        <mesh name="Stairs_L004" geometry={nodes.Stairs_L004.geometry} material={materials.stage_mat} position={[0, 0, -0.58]} />
        <mesh name="Stairs_L005" geometry={nodes.Stairs_L005.geometry} material={materials.stage_mat} position={[0, 0, -0.58]} />
        <mesh name="Stairs_L006" geometry={nodes.Stairs_L006.geometry} material={materials.stage_mat} position={[0, 0, -0.58]} />
        <mesh name="Stairs_R001" geometry={nodes.Stairs_R001.geometry} material={materials.stage_mat} position={[6, 0.95, 2]} scale={[0.5, 0.21, 1.97]} />
        <mesh name="Stairs_R002" geometry={nodes.Stairs_R002.geometry} material={materials.stage_mat} position={[6, 0.95, 2]} scale={[0.5, 0.21, 1.97]} />
        <mesh name="Stairs_R003" geometry={nodes.Stairs_R003.geometry} material={materials.stage_mat} position={[6, 0.95, 2]} scale={[0.5, 0.21, 1.97]} />
        <mesh name="Stairs_R004" geometry={nodes.Stairs_R004.geometry} material={materials.stage_mat} position={[6, 0.95, 2]} scale={[0.5, 0.21, 1.97]} />
        <mesh name="Stairs_R005" geometry={nodes.Stairs_R005.geometry} material={materials.stage_mat} position={[6, 0.95, 2]} scale={[0.5, 0.21, 1.97]} />
        <mesh name="Stairs_R006" geometry={nodes.Stairs_R006.geometry} material={materials.stage_mat} position={[6, 0.95, 2]} scale={[0.5, 0.21, 1.97]} />
        <mesh name="Screen" geometry={nodes.Screen.geometry} material={materials.screen} position={[0, 4.01, -2.17]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[6, 1.88, 2.1]} />
        <mesh name="P" geometry={nodes.P.geometry} material={materials.publifest_text_mat} position={[10, 0, 0]} />
        <mesh name="U" geometry={nodes.U.geometry} material={materials.publifest_text_mat} position={[10, 0, 0]} />
        <mesh name="B" geometry={nodes.B.geometry} material={materials.publifest_text_mat} position={[10, 0, 0]} />
        <mesh name="L" geometry={nodes.L.geometry} material={materials.publifest_text_mat} position={[10, 0, 0]} />
        <mesh name="F" geometry={nodes.F.geometry} material={materials.publifest_text_mat} position={[10, 0, 0]} />
        <mesh name="I" geometry={nodes.I.geometry} material={materials.publifest_text_mat} position={[10, 0, 0]} />
        <mesh name="S" geometry={nodes.S.geometry} material={materials.publifest_text_mat} position={[10, 0, 0]} />
        <mesh name="T" geometry={nodes.T.geometry} material={materials.publifest_text_mat} position={[10, 0, 0]} />
        <mesh name="E" geometry={nodes.E.geometry} material={materials.publifest_text_mat} position={[10, 0, 0]} />
        <mesh name="logo_tenso_geo" geometry={nodes.logo_tenso_geo.geometry} material={materials['Material.001']} morphTargetDictionary={nodes.logo_tenso_geo.morphTargetDictionary} morphTargetInfluences={nodes.logo_tenso_geo.morphTargetInfluences} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/congressi-transformed.glb')
