/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 W:\Publifest\publifest-3d-r3f\public\models\ground.glb --output W:\Publifest\publifest-3d-r3f\public\models\ground.glb --keepnames --keepgroups --shadows --instance --printwidth 200 --root W:\Publifest\publifest-3d-r3f\public\models\ --transform --debug
*/

import * as THREE from 'three'
import {useEffect, useRef} from 'react'
import {useFrame} from '@react-three/fiber'
import {useScroll, useGLTF, useAnimations, MeshReflectorMaterial} from '@react-three/drei'

export default function Ground(props) {

  const scroll = useScroll()

  const group = useRef()
  const {nodes, materials, animations} = useGLTF('models/ground-transformed.glb')
  const {actions} = useAnimations(animations, group)

  // useEffect(() => void (actions['ground'].play().paused = true), [actions])

  // useFrame((state, delta) => {
  //   const action = actions['ground']
  //   // action.time = THREE.MathUtils.damp(action.time, (action.getClip().duration / 2) * scroll.offset * props.multiplier, 8, delta)
  //   action.time = 50
  // })

  return (

        <mesh
          name="GroundDisk"
          castShadow
          receiveShadow
          position={[0, 0, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={10}
        >
          <planeBufferGeometry attach="geometry" args={[100, 100]} />
          <MeshReflectorMaterial
            resolution={2048}
            mixBlur={10}
            mixStrength={3} 
            blur={[2000, 2000]}
            minDepthThreshold={0.4}
            maxDepthThreshold={1.4}
            depthScale={0}
            depthToBlurRatioBias={0.1}
            attach={'material'}
            color="#ffffff"
            roughness={0.4}
            metalness={0.1}
          />
        </mesh>

  )
}

useGLTF.preload('models/ground-transformed.glb')

{/*          
<MeshReflectorMaterial
  resolution={2048}
  mixBlur={10}
  mixStrength={1}
  blur={[2000, 2000]}
  minDepthThreshold={0.4}
  maxDepthThreshold={1.4}
  depthScale={0}
  color="#cccccc"
  metalness={0.1}
  roughness={0.9}
/> */}